export enum RequestStatus {
  NOT_ANSWERED = 'NOT_ANSWERED',
  AWAITING_CLIENT = 'AWAITING_CLIENT',
  FOLLOW_UP = 'FOLLOW_UP',
  AWAITING_DOCS = 'AWAITING_DOCS',
  AWAITING_BANK_REP = 'AWAITING_BANK_REP',
  SOLD = 'SOLD',
  NOT_SOLD = 'NOT_SOLD',
}

